name: Cron pipeline

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cron_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fullstack-11.herokuapp.com/health
          max-attempts: 2
          retry-delay: 5s